[package]
name = "note-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = '*'
crossterm ='*'

serde = { version = '*', features = ['derive'] }
serde_json = '*'

chrono = { version = "*", features = ['serde']}
